# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Foundry
version:      0.08
version_from: lib/Mail/Foundry.pm
installdirs:  site
requires:
    HTML::Form:                    1
    LWP::UserAgent:                2
    URI::Escape:                   3.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
